#!/usr/bin/env python3
"""
Build docs/supabase-account-display-names.sql from ground_truth.txt.
Uses the first character listed per account (in ground_truth file order) as
that account's display name. Reads data/accounts.csv for account_id -> toon_names.
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GROUND_TRUTH = ROOT / "ground_truth.txt"
ACCOUNTS_CSV = ROOT / "data" / "accounts.csv"
OUT_SQL = ROOT / "docs" / "supabase-account-display-names.sql"


def parse_ground_truth_order(path: Path) -> list[str]:
    """Return character names in order of appearance in ground_truth (first column, strip ' [+]')."""
    names = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.startswith("\t"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                continue
            raw = parts[1].strip()  # e.g. "Inacht [+]" or "Dula Allazaward [+]"
            name = re.sub(r"\s*\[\+\]\s*$", "", raw).strip()
            if name and name != "Name":
                names.append(name)
    return names


def load_account_toons(path: Path) -> dict[str, list[str]]:
    """Return { account_id: [toon_name, ...] }."""
    account_toons: dict[str, list[str]] = {}
    with open(path, encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            aid = (row.get("account_id") or "").strip()
            toons_str = (row.get("toon_names") or "").strip()
            toons = [n.strip() for n in toons_str.split(",") if n.strip()]
            if aid:
                account_toons[aid] = toons
    return account_toons


def main() -> None:
    gt_order = parse_ground_truth_order(GROUND_TRUTH)
    account_toons = load_account_toons(ACCOUNTS_CSV)

    # character name -> account_id (first account that has this toon)
    name_to_account: dict[str, str] = {}
    for aid, toons in account_toons.items():
        for t in toons:
            if t and t not in name_to_account:
                name_to_account[t] = aid

    # For each account, first character in ground_truth order that belongs to it = display_name
    account_display: dict[str, str] = {}
    for name in gt_order:
        aid = name_to_account.get(name)
        if not aid or aid in account_display:
            continue
        account_display[aid] = name

    # Any account with toons but no display_name: use first toon
    for aid, toons in account_toons.items():
        if aid in account_display or not toons:
            continue
        account_display[aid] = toons[0]

    lines = [
        "-- Set account display names from ground_truth.txt (first character per account in file order).",
        "-- Run in Supabase SQL Editor after accounts are imported. Safe to re-run.",
        "-- Generated by scripts/build_account_display_names_from_ground_truth.py",
        "",
    ]
    for aid in sorted(account_display.keys(), key=lambda x: (x == "_no_account_", x)):
        if aid == "_no_account_":
            continue
        display = account_display[aid]
        esc = display.replace("'", "''")
        lines.append(f"UPDATE accounts SET display_name = '{esc}' WHERE account_id = '{aid}';")

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL} ({len(lines) - 5} UPDATEs)")


if __name__ == "__main__":
    main()
